[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/menu"
  to = "/.netlify/functions/menu"
  status = 200
  force = true

[[redirects]]
  from = "/api/order"
  to = "/.netlify/functions/order"
  status = 200
  force = true

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders-admin"
  status = 200
  force = true

[[redirects]]
  from = "/api/order-status"
  to = "/.netlify/functions/order-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/signup"
  to = "/.netlify/functions/auth-signup"
  status = 200
  force = true
